/* Casos de test del Level 3 de ESTA app (Habits: used to / usually / be used to / get used to).
   full: respuesta modelo SIN contracciones · pos: deben ACEPTARSE · neg: deben FALLAR */
module.exports = {
  used_to_past_l3_0: { full: "I used to play football every day.",
    pos: ["I would play football every day.", "Every day I used to play soccer.", "She used to play football every day.", "I used to play football each day"],
    neg: ["I use to play football every day.", "I used to playing football every day.", "I am used to playing football every day.", "I played football every day.", "I usually play football every day.", "I used play football every day.", "I was used to play football every day."] },
  used_to_past_l3_1: { full: "I did not use to like broccoli.",
    pos: ["I didn't use to like broccoli.", "I never used to like broccoli.", "Before, I didn't use to like broccoli.", "I didnt use to like broccoli before", "I used not to like broccoli."],
    neg: ["I didn't used to like broccoli.", "I didn't like broccoli.", "I don't use to like broccoli.", "I wasn't used to like broccoli.", "I would not like broccoli.", "I didn't use to liking broccoli.", "I didn't use like broccoli."] },
  used_to_past_l3_2: { full: "Did you use to have long hair?",
    pos: ["did you use to have long hair", "DID YOU USE TO HAVE LONG HAIR?"],
    neg: ["Did you used to have long hair?", "Did you have long hair?", "You used to have long hair?", "Were you used to have long hair?", "Did you use to having long hair?", "Did you use to have the hair long?", "Do you use to have long hair?"] },
  used_to_past_l3_3: { full: "My father used to drive to work, but now he goes by metro.",
    pos: ["My dad used to drive to work, but now he takes the underground.", "My father would drive to work, but he now goes on the metro.", "My father used to drive to work but he takes the subway now"],
    neg: ["My father drove to work, but now he goes by metro.", "My father use to drive to work, but now he goes by metro.", "My father used to drive to work, but now he go by metro.", "My father used to drive to work, but now he is used to go by metro.", "My father used to driving to work, but now he goes by metro.", "My father used to drive to work, but now he goes in metro."] },
  used_to_past_l3_4: { full: "We used to live in a big house.",
    pos: ["Before, we used to live in a large house.", "We used to live in a big house before.", "we used to live in a big house"],
    neg: ["We lived in a big house.", "We use to live in a big house.", "We used to living in a big house.", "We were used to live in a big house.", "We would live in a big house.", "We used to live in a house big.", "We usually live in a big house."] },
  used_to_past_l3_5: { full: "There used to be a cinema in my village.",
    pos: ["There used to be a cinema in my town.", "Before, there used to be a cinema in my village.", "There used to be a movie theater in my town."],
    neg: ["There was a cinema in my village.", "There use to be a cinema in my village.", "It used to be a cinema in my village.", "There used to have a cinema in my village.", "There used to being a cinema in my village.", "There would be a cinema in my village."] },
  used_to_past_l3_6: { full: "Where did you use to go on holiday?",
    pos: ["Where did you use to go for your holidays?", "Where did you use to go on vacation?"],
    neg: ["Where did you used to go on holiday?", "Where did you go on holiday?", "Where you used to go on holiday?", "Where did you use to going on holiday?", "Where do you use to go on holiday?", "Where were you used to go on holiday?"] },
  used_to_past_l3_7: { full: "I did not use to watch horror films when I was little.",
    pos: ["I never used to watch scary movies when I was a child.", "When I was little, I didn't use to watch horror films.", "I would never watch horror films when I was young."],
    neg: ["I didn't watch horror films when I was little.", "I didn't used to watch horror films when I was little.", "I don't use to watch horror films when I was little.", "I didn't use to watch horror films when I am little.", "I wasn't used to watch horror films when I was little.", "I didn't use to watching horror films when I was little."] },
  used_to_past_l3_8: { full: "My brother used to have a beard, but he shaved it off.",
    pos: ["My brother used to have a beard, but he shaved it.", "My brother used to have a beard but he shaved it off"],
    neg: ["My brother had a beard, but he shaved it off.", "My brother use to have a beard, but he shaved it off.", "My brother used to have a beard, but he shaves it off.", "My brother was used to have a beard, but he shaved it off.", "My brother used to having a beard, but he shaved it off.", "My brother used to have beard, but he shaved it off."] },
  used_to_past_l3_9: { full: "People used to write letters.",
    pos: ["People would write letters.", "people used to write letters"],
    neg: ["People use to write letters.", "People wrote letters.", "People used to writing letters.", "People were used to write letters.", "People usually write letters.", "People used to wrote letters."] },

  usually_present_l3_0: { full: "I usually get up at seven.",
    pos: ["I normally get up at 7.", "I generally get up at seven o'clock.", "I usually get up at 7:00"],
    neg: ["I used to get up at seven.", "I get usually up at seven.", "I usually gets up at seven.", "I am usually get up at seven.", "Usually I get at seven up.", "I usually get up at eight.", "I use to get up at seven."] },
  usually_present_l3_1: { full: "I used to get up at nine.",
    pos: ["Before, I used to get up at nine.", "I would get up at 9.", "I used to get up at nine before."],
    neg: ["I got up at nine.", "I usually get up at nine.", "I use to get up at nine.", "I used to getting up at nine.", "I am used to get up at nine.", "I used to get up at nine tomorrow."] },
  usually_present_l3_2: { full: "I usually study in the afternoon.",
    pos: ["I normally study in the evening.", "I generally study in the afternoon"],
    neg: ["I used to study in the afternoon.", "I usually studies in the afternoon.", "I study usually in the afternoon.", "I am usually study in the afternoon.", "I usually study on the afternoon.", "I usually study in afternoon."] },
  usually_present_l3_3: { full: "I used to study at night.",
    pos: ["I would study in the evening.", "She used to study at night.", "I used to study in the evening"],
    neg: ["I studied at night.", "I usually study at night.", "I use to study at night.", "I used to studying at night.", "I was used to study at night.", "I used to study in the night."] },
  usually_present_l3_4: { full: "What do you usually do at weekends?",
    pos: ["What do you normally do at the weekend?", "What do you usually do on weekends?", "At weekends, what do you usually do?"],
    neg: ["What did you use to do at weekends?", "What do you usually at weekends?", "What you usually do at weekends?", "What are you usually doing at weekends?", "What do you usually make at weekends?", "What does you usually do at weekends?"] },
  usually_present_l3_5: { full: "My sister does not usually eat meat.",
    pos: ["My sister doesn't usually eat meat.", "My sister usually doesn't eat meat.", "My sister doesnt normally eat meat"],
    neg: ["My sister doesn't usually eats meat.", "My sister don't usually eat meat.", "My sister usually not eat meat.", "My sister didn't use to eat meat.", "My sister isn't used to eat meat.", "My sister doesn't eat usually meat."] },
  usually_present_l3_6: { full: "I did not use to like coffee, but now I drink it every day.",
    pos: ["I never used to like coffee, but now I have it every day.", "I didn't use to like coffee, but now I drink coffee every day.", "I didnt use to like coffee but I drink it every day now"],
    neg: ["I didn't like coffee, but now I drink it every day.", "I didn't used to like coffee, but now I drink it every day.", "I didn't use to like coffee, but now I drink every day.", "I didn't use to like coffee, but now I am used to drink it every day.", "I didn't use to like coffee, but now I drinks it every day.", "I don't use to like coffee, but now I drink it every day."] },
  usually_present_l3_7: { full: "Nowadays people usually use their mobile for everything.",
    pos: ["These days people usually use their phones for everything.", "People normally use their mobile phones for everything nowadays.", "Today people generally use mobiles for everything."],
    neg: ["Nowadays people used to use their mobile for everything.", "Nowadays people usually uses their mobile for everything.", "Nowadays people are usually use their mobile for everything.", "Nowadays people use usually their mobile for everything.", "Nowadays people usually use their mobile for all.", "Nowadays people usually use the mobile for everything."] },
  usually_present_l3_8: { full: "Did you use to walk to school?",
    pos: ["Did you use to go to school on foot?", "did you use to walk to school"],
    neg: ["Did you walk to school?", "Did you used to walk to school?", "Do you usually walk to school?", "You used to walk to school?", "Did you use to walking to school?", "Did you use to walk at school?"] },
  usually_present_l3_9: { full: "We usually have dinner at nine, but we used to have dinner at eight.",
    pos: ["We usually have dinner at nine, but before we used to have it at eight.", "We normally eat dinner at 9, but we used to have dinner at 8.", "We usually have supper at nine but we would have it at eight"],
    neg: ["We usually have dinner at nine, but we had dinner at eight.", "We used to have dinner at nine, but we usually have dinner at eight.", "We usually have dinner at nine, but we use to have dinner at eight.", "We usually have dinner at nine, but we used to having dinner at eight.", "We usually has dinner at nine, but we used to have dinner at eight.", "We usually have dinner at nine, but we were used to have dinner at eight."] },

  be_used_to_l3_0: { full: "I am used to getting up early.",
    pos: ["I'm used to getting up early.", "I am accustomed to getting up early.", "Im used to waking up early in the morning"],
    neg: ["I am used to get up early.", "I used to get up early.", "I am use to getting up early.", "I get used to getting up early.", "I am used to getting early up.", "I usually get up early.", "I am used getting up early."] },
  be_used_to_l3_1: { full: "She is used to the cold.",
    pos: ["She's used to the cold weather.", "She is accustomed to cold weather.", "Shes used to the cold"],
    neg: ["She used to the cold.", "She is use to the cold.", "She is used the cold.", "She uses to the cold.", "She is used to cold the.", "She is used to the hot."] },
  be_used_to_l3_2: { full: "We are not used to so much noise.",
    pos: ["We aren't used to so much noise.", "We're not used to this much noise.", "We are not accustomed to all this noise."],
    neg: ["We didn't use to so much noise.", "We are not use to so much noise.", "We are not used to so many noise.", "We don't used to so much noise.", "We are not used so much noise.", "We are not used to such noise much."] },
  be_used_to_l3_3: { full: "Are you used to driving on the left?",
    pos: ["Are you used to driving on the left-hand side?", "Are you accustomed to driving on the left side of the road?", "are you used to driving on the left"],
    neg: ["Are you used to drive on the left?", "Did you use to drive on the left?", "You are used to driving on the left?", "Are you use to driving on the left?", "Are you used to driving on the right?", "Are you used to driving in the left?"] },
  be_used_to_l3_4: { full: "My mother is a nurse, so she is used to working at night.",
    pos: ["My mum is a nurse, so she's used to working nights.", "My mother is a nurse so she is accustomed to working the night shift"],
    neg: ["My mother is a nurse, so she is used to work at night.", "My mother is a nurse, so she used to work at night.", "My mother is nurse, so she is used to working at night.", "My mother is a nurse, so she is use to working at night.", "My mother is a nurse, so she gets used to working at night.", "My mother is a nurse, so she is used to working in the night."] },
  be_used_to_l3_5: { full: "I am not used to this timetable.",
    pos: ["I'm not used to this timetable.", "I am not used to this schedule.", "Im not accustomed to this timetable"],
    neg: ["I didn't use to this timetable.", "I am not use to this timetable.", "I am not used this timetable.", "I not used to this timetable.", "I am not used to that timetable.", "I don't used to this timetable."] },
  be_used_to_l3_6: { full: "My grandparents are not used to using the mobile.",
    pos: ["My grandparents aren't used to using mobile phones.", "My grandparents are not accustomed to using their mobiles.", "My grandma and grandpa aren't used to using a mobile"],
    neg: ["My grandparents are not used to use the mobile.", "My grandparents didn't use to use the mobile.", "My grandparents is not used to using the mobile.", "My grandparents are not use to using the mobile.", "My grandparents don't get used to using the mobile.", "My grandparents are not used using the mobile."] },
  be_used_to_l3_7: { full: "He is used to running long distances.",
    pos: ["He's used to running long distances.", "He is accustomed to running long distances"],
    neg: ["He is used to run long distances.", "He used to run long distances.", "He is use to running long distances.", "He gets used to running long distances.", "He is used to running distances long.", "He is used to runing long distances."] },
  be_used_to_l3_8: { full: "When I lived in London, I was used to the rain.",
    pos: ["I was used to the rain when I lived in London.", "When I was living in London, I was accustomed to the rain.", "When I used to live in London I was used to the rain"],
    neg: ["When I lived in London, I used to the rain.", "When I lived in London, I am used to the rain.", "When I lived in London, I was use to the rain.", "When I live in London, I was used to the rain.", "When I lived in London, I was used the rain.", "When I lived on London, I was used to the rain."] },
  be_used_to_l3_9: { full: "Students are used to doing a lot of exams.",
    pos: ["Students are used to taking lots of tests.", "The students are accustomed to sitting many exams.", "Students are used to doing a lot of exams"],
    neg: ["Students are used to do a lot of exams.", "Students used to do a lot of exams.", "Students are used to making a lot of exams.", "Students is used to doing a lot of exams.", "Students are use to doing a lot of exams.", "Students are used to doing a lot of exam."] },

  get_used_to_l3_0: { full: "I am getting used to living alone.",
    pos: ["I'm getting used to living on my own.", "I am getting accustomed to living by myself.", "Im getting used to living alone"],
    neg: ["I am getting used to live alone.", "I get used to living alone.", "I am used to living alone.", "I am getting use to living alone.", "I am geting used to living alone.", "I am getting used living alone.", "I used to live alone."] },
  get_used_to_l3_1: { full: "You will soon get used to the new timetable.",
    pos: ["You'll get used to the new schedule soon.", "Soon you will get used to the new timetable.", "You will soon become accustomed to the new timetable"],
    neg: ["You will soon get used the new timetable.", "You will soon be used to the new timetable.", "You soon get used to the new timetable.", "You will soon get use to the new timetable.", "You will soon used to the new timetable.", "You will soon get used to the new time."] },
  get_used_to_l3_2: { full: "It was hard for me to get used to driving on the left.",
    pos: ["It took me a long time to get used to driving on the left.", "I found it difficult to get used to driving on the left-hand side.", "It was difficult to get used to driving on the left"],
    neg: ["It was hard for me to get used to drive on the left.", "It was hard for me to be used to driving on the left.", "It was hard for me to use to driving on the left.", "It was hard for me get used to driving on the left.", "It is hard for me to get used to driving on the left.", "It was hard for me to get use to driving on the left."] },
  get_used_to_l3_3: { full: "Have you got used to your new school yet?",
    pos: ["Have you gotten used to your new school yet?", "Have you already got used to your new school?", "Have you got used to your new high school?"],
    neg: ["Are you used to your new school yet?", "Have you get used to your new school yet?", "Did you get used to your new school yet?", "Have you got use to your new school yet?", "Have you got used your new school yet?", "You have got used to your new school yet?"] },
  get_used_to_l3_4: { full: "I will never get used to the noise in this city.",
    pos: ["I'll never get used to the noise of this city.", "Ill never get used to the noise in this city"],
    neg: ["I will never be used to the noise in this city.", "I will never get used the noise in this city.", "I never get used to the noise in this city.", "I will never get use to the noise in this city.", "I won't never get used to the noise in this city.", "I will never get used to the noise in that city."] },
  get_used_to_l3_5: { full: "She quickly got used to having dinner late.",
    pos: ["He soon got used to eating dinner late.", "She got used to having dinner late very quickly.", "She quickly got used to having supper late"],
    neg: ["She quickly got used to have dinner late.", "She quickly was used to having dinner late.", "She quickly used to have dinner late.", "She quickly gets used to having dinner late.", "She quickly got use to having dinner late.", "She quickly got used to having dinner lately."] },
  get_used_to_l3_6: { full: "We are getting used to the weather in Ireland.",
    pos: ["We're getting used to the Irish weather.", "We are getting used to the climate in Ireland", "Were getting used to Ireland's weather"],
    neg: ["We get used to the weather in Ireland.", "We are used to the weather in Ireland.", "We are getting used the weather in Ireland.", "We are getting use to the weather in Ireland.", "We is getting used to the weather in Ireland.", "We are getting used to the weather of Ireland in."] },
  get_used_to_l3_7: { full: "It is difficult to get used to getting up early.",
    pos: ["Getting used to getting up early is hard.", "It's hard to get used to waking up early.", "Its difficult to get used to getting up early"],
    neg: ["It is difficult to get used to get up early.", "It is difficult to be used to getting up early.", "It is difficult get used to getting up early.", "It is difficult to get use to getting up early.", "Is difficult to get used to getting up early.", "It is difficult to get used to getting early up."] },
  get_used_to_l3_8: { full: "My grandmother can not get used to using the computer.",
    pos: ["My grandma can't get used to using computers.", "My grandmother isn't getting used to using the computer.", "My granny cannot get used to using a computer."],
    neg: ["My grandmother can't get used to use the computer.", "My grandmother can't be used to using the computer.", "My grandmother can't gets used to using the computer.", "My grandmother can't get use to using the computer.", "My grandmother doesn't used to using the computer.", "My grandmother can't get used using the computer."] },
  get_used_to_l3_9: { full: "In the end I got used to wearing a uniform.",
    pos: ["Eventually I got used to wearing the uniform.", "Finally, I got used to wearing uniform.", "I got used to wearing a uniform in the end."],
    neg: ["In the end I got used to wear a uniform.", "In the end I was used to wearing a uniform.", "In the end I used to wear a uniform.", "In the end I get used to wearing a uniform.", "In the end I got use to wearing a uniform.", "At the end I got used to wearing a uniform."] },

  master_habits_l3_0: { full: "I usually go to the gym three times a week.",
    pos: ["I normally go to the gym three times per week.", "I usually go to the gym 3 times a week.", "I generally go to the gym three times every week"],
    neg: ["I used to go to the gym three times a week.", "I usually goes to the gym three times a week.", "I go usually to the gym three times a week.", "I am usually go to the gym three times a week.", "I usually go to gym three times a week.", "I usually go to the gym three times for week."] },
  master_habits_l3_1: { full: "I used to go to school by bike.",
    pos: ["I used to cycle to school.", "I would ride my bike to school.", "Before, I used to go to school by bicycle."],
    neg: ["I went to school by bike.", "I use to go to school by bike.", "I used to going to school by bike.", "I am used to go to school by bike.", "I used to go to school in bike.", "I usually go to school by bike."] },
  master_habits_l3_2: { full: "I am used to studying with music.",
    pos: ["I'm used to studying while listening to music.", "I am accustomed to studying with music on."],
    neg: ["I am used to study with music.", "I used to study with music.", "I am use to studying with music.", "I get used to studying with music.", "I am used studying with music.", "I am used to studying with the music."] },
  master_habits_l3_3: { full: "I am getting used to my new school.",
    pos: ["I'm getting used to my new high school.", "I am getting accustomed to my new school"],
    neg: ["I get used to my new school.", "I am used to my new school.", "I am getting used my new school.", "I am getting use to my new school.", "I am geting used to my new school.", "I am getting used to my old school."] },
  master_habits_l3_4: { full: "Did you use to play in the street?",
    pos: ["Did you use to play in the streets?", "did you use to play in the street"],
    neg: ["Did you play in the street?", "Did you used to play in the street?", "You used to play in the street?", "Did you use to playing in the street?", "Did you use to play on the street?", "Do you use to play in the street?"] },
  master_habits_l3_5: { full: "I am not used to going to bed so late.",
    pos: ["I'm not used to going to bed this late.", "I am not accustomed to going to bed that late."],
    neg: ["I am not used to go to bed so late.", "I didn't use to go to bed so late.", "I am not use to going to bed so late.", "I don't get used to going to bed so late.", "I am not used to going to the bed so late.", "I am not used going to bed so late."] },
  master_habits_l3_6: { full: "My brother did not use to do sport, but now he runs every day.",
    pos: ["My brother never used to do sports, but now he goes running every day.", "My brother didn't use to do any sport, but he goes for a run every day now."],
    neg: ["My brother didn't do sport, but now he runs every day.", "My brother didn't used to do sport, but now he runs every day.", "My brother didn't use to do sport, but now he run every day.", "My brother didn't use to make sport, but now he runs every day.", "My brother isn't used to do sport, but now he runs every day.", "My brother didn't use to do sport, but now he is used to run every day."] },
  master_habits_l3_7: { full: "I will never get used to this cold.",
    pos: ["I'll never get used to this cold weather.", "Ill never get used to this cold"],
    neg: ["I will never be used to this cold.", "I will never get used this cold.", "I never get used to this cold.", "I will never get use to this cold.", "I won't never get used to this cold.", "I will never get used to that cold."] },
  master_habits_l3_8: { full: "I do not usually have breakfast.",
    pos: ["I don't usually have breakfast.", "I usually don't eat breakfast.", "I dont normally have breakfast"],
    neg: ["I don't usually having breakfast.", "I didn't use to have breakfast.", "I not usually have breakfast.", "I usually no have breakfast.", "I am not usually have breakfast.", "I don't usually take breakfast."] },
  master_habits_l3_9: { full: "My parents used to work in Madrid.",
    pos: ["my parents used to work in madrid", "MY PARENTS USED TO WORK IN MADRID."],
    neg: ["My parents worked in Madrid.", "My parents use to work in Madrid.", "My parents used to working in Madrid.", "My parents were used to work in Madrid.", "My parents usually work in Madrid.", "My parents used to work at Madrid."] }
};
